services:
  database:
    build: 
      context: ./db_init_service
    container_name: postgres_database
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_project
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - ai_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  python_service:
    build:
      context: ./nlp_api_service
    container_name: python_nlp
    environment:
      DB_HOST: database  
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: ai_project
    depends_on:
      database:
        condition: service_healthy
    networks:
      - ai_network
networks:
  ai_network:
    driver: bridge
